apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: webserver-loadbalancer
spec:
    replicas: 2
    selector:
        matchLabels:
            app: webserver-loadbalancer
    template:
        metadata:
            labels:
                app: webserver-loadbalancer
        spec:
            serviceAccountName: summer
            imagePullSecrets:
            - name: chenlipeng
            containers:
            - name: webserver
              image: registry.cn-beijing.aliyuncs.com/chenlipeng/webserver:0.0.3

---

apiVersion: v1
kind: Service
metadata:
    labels:
        app: webserver-loadbalancer
    name: webserver-loadbalancer
    namespace: default
spec:
    type: LoadBalancer
    sessionAffinity: None
    ports:
        - port: 443
          targetPort: 9999
          #nodePort: 30000
    selector:
        app: webserver-loadbalancer
